
import React, { useState } from 'react';
import { Priority, ColumnId, Task } from '../types';
import { SparklesIcon, FileTextIcon, SendIcon, CheckIcon, PlusIcon, DownloadIcon, XIcon, UsersIcon } from './Icons';
import * as AIService from '../services/ai';

interface MeetingStudioProps {
  onAddTask: (task: Task) => void;
}

export const MeetingStudio: React.FC<MeetingStudioProps> = ({ onAddTask }) => {
  const [rawNotes, setRawNotes] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [minutes, setMinutes] = useState<{ html: string, extractedTasks: any[] } | null>(null);

  const handleProcess = async () => {
    if (!rawNotes.trim()) return;
    setIsProcessing(true);
    try {
      const result = await AIService.processMeetingNotes(rawNotes);
      setMinutes(result);
    } catch (e) {
      console.error(e);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleSyncTask = (taskData: any) => {
    const newTask: Task = {
      id: crypto.randomUUID(),
      title: taskData.title,
      description: "Extracted from meeting minutes.",
      priority: taskData.priority as Priority,
      columnId: ColumnId.Todo,
      subtasks: [],
      images: [],
      comments: [],
      attachments: [],
      tags: ['#meeting-sync'],
      deadline: taskData.deadline ? new Date(taskData.deadline).getTime() : undefined,
      createdAt: Date.now()
    };
    onAddTask(newTask);
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>Meeting Minutes</title>
          <style>
            body { font-family: 'Inter', sans-serif; padding: 40px; color: #1c1917; line-height: 1.6; }
            h1 { color: #4f46e5; border-bottom: 2px solid #f5f5f4; padding-bottom: 10px; }
            h2 { color: #44403c; margin-top: 30px; border-left: 4px solid #4f46e5; padding-left: 15px; }
            ul { padding-left: 20px; }
            li { margin-bottom: 8px; }
            .footer { margin-top: 50px; font-size: 10px; color: #a8a29e; text-align: center; border-top: 1px solid #f5f5f4; padding-top: 20px; }
          </style>
        </head>
        <body>
          ${minutes?.html}
          <div class="footer">Generated by MindDrop Intelligence Studio</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="flex-1 overflow-hidden flex flex-col bg-stone-50 dark:bg-stone-950 p-6 sm:p-12">
      <div className="max-w-6xl mx-auto w-full flex-1 flex flex-col gap-8">
        
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
          <div className="space-y-1">
             <div className="flex items-center gap-3 text-indigo-600">
               <UsersIcon className="w-6 h-6" />
               <span className="text-[10px] font-black uppercase tracking-[0.4em]">Intelligence Studio</span>
             </div>
             <h1 className="text-4xl font-black text-stone-900 dark:text-white">Meeting Studio</h1>
          </div>
          {minutes && (
            <div className="flex items-center gap-3">
              <button onClick={() => setMinutes(null)} className="px-6 py-3 rounded-2xl bg-stone-200 dark:bg-stone-800 text-stone-600 dark:text-stone-300 text-xs font-black uppercase tracking-widest hover:opacity-80 transition-all">New Meeting</button>
              <button onClick={handlePrint} className="px-6 py-3 rounded-2xl bg-stone-900 dark:bg-stone-100 text-white dark:text-stone-900 text-xs font-black uppercase tracking-widest flex items-center gap-2 shadow-xl active:scale-95 transition-all">
                <DownloadIcon className="w-4 h-4" /> Export Document
              </button>
            </div>
          )}
        </div>

        {!minutes ? (
          <div className="flex-1 flex flex-col bg-white dark:bg-stone-900 rounded-[2.5rem] shadow-2xl border border-stone-200 dark:border-white/5 overflow-hidden animate-in slide-in-from-bottom-4 duration-500">
            <div className="flex-1 p-8 flex flex-col gap-6">
              <div className="flex items-center justify-between">
                <label className="text-[11px] font-black text-stone-400 uppercase tracking-[0.3em]">Raw Transcription / Notes</label>
                <div className="flex items-center gap-2 text-[10px] font-bold text-indigo-500">
                  <SparklesIcon className="w-4 h-4" /> AI Powered Structuring
                </div>
              </div>
              <textarea 
                value={rawNotes}
                onChange={e => setRawNotes(e.target.value)}
                placeholder="Paste your meeting notes, speaker transcripts, or messy scribbles here..."
                className="flex-1 bg-stone-50/50 dark:bg-stone-800/50 p-8 rounded-3xl border border-stone-100 dark:border-white/5 focus:border-indigo-500/30 outline-none text-lg text-stone-700 dark:text-stone-300 resize-none leading-relaxed transition-all"
              />
              <button 
                onClick={handleProcess}
                disabled={isProcessing || !rawNotes.trim()}
                className="w-full py-6 bg-indigo-600 text-white rounded-[1.75rem] font-black uppercase tracking-[0.2em] text-sm shadow-2xl shadow-indigo-500/20 active:scale-95 transition-all disabled:opacity-50 flex items-center justify-center gap-4"
              >
                {isProcessing ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    Generating Document...
                  </>
                ) : (
                  <>
                    <SparklesIcon className="w-6 h-6" />
                    Process Meeting Minutes
                  </>
                )}
              </button>
            </div>
          </div>
        ) : (
          <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 gap-8 overflow-hidden">
            
            {/* The Document View */}
            <div className="lg:col-span-2 bg-white dark:bg-stone-900 rounded-[2.5rem] shadow-xl border border-stone-200 dark:border-white/5 overflow-y-auto no-scrollbar p-12 animate-in fade-in slide-in-from-left-4 duration-500">
               <div 
                 className="prose prose-stone dark:prose-invert max-w-none"
                 dangerouslySetInnerHTML={{ __html: minutes.html }}
               />
            </div>

            {/* The Actions Sidebar */}
            <div className="bg-stone-100 dark:bg-stone-800/40 rounded-[2.5rem] border border-stone-200 dark:border-white/5 p-8 flex flex-col gap-8 animate-in fade-in slide-in-from-right-4 duration-500">
               <div className="space-y-1">
                 <label className="text-[10px] font-black text-stone-400 uppercase tracking-[0.3em]">Extracted Actions</label>
                 <h3 className="text-lg font-black text-stone-900 dark:text-white">Workflow Sync</h3>
               </div>

               <div className="flex-1 overflow-y-auto space-y-4 no-scrollbar">
                  {minutes.extractedTasks.map((t, i) => (
                    <div key={i} className="bg-white dark:bg-stone-900 p-5 rounded-2xl border border-stone-100 dark:border-white/5 group relative overflow-hidden">
                       <div className={`absolute top-0 left-0 w-1 h-full ${
                         t.priority === 'Critical' ? 'bg-rose-500' : 
                         t.priority === 'High' ? 'bg-orange-500' : 'bg-indigo-500'
                       }`} />
                       <p className="text-sm font-bold text-stone-800 dark:text-stone-200 mb-3 leading-snug">{t.title}</p>
                       <div className="flex items-center justify-between">
                          <span className="text-[10px] font-black uppercase text-stone-400 bg-stone-50 dark:bg-stone-800 px-2.5 py-1 rounded-lg">
                            {t.deadline || 'No Date'}
                          </span>
                          <button 
                            onClick={() => handleSyncTask(t)}
                            className="p-2 bg-indigo-600 text-white rounded-xl shadow-lg hover:scale-110 active:scale-95 transition-all"
                            title="Add to Board"
                          >
                            <PlusIcon className="w-4 h-4" />
                          </button>
                       </div>
                    </div>
                  ))}
                  {minutes.extractedTasks.length === 0 && (
                    <div className="h-full flex flex-col items-center justify-center opacity-20 py-12">
                      <CheckIcon className="w-12 h-12 mb-4" />
                      <p className="text-[10px] font-black uppercase tracking-widest">No actions detected</p>
                    </div>
                  )}
               </div>

               <div className="p-4 bg-indigo-600/5 rounded-2xl border border-indigo-600/10">
                 <p className="text-[10px] text-indigo-600 dark:text-indigo-400 font-bold leading-relaxed">
                   AI analyzed your notes and found {minutes.extractedTasks.length} potential tasks. Sync them to your board to start executing.
                 </p>
               </div>
            </div>

          </div>
        )}
      </div>
    </div>
  );
};
